init:
    conda env create -f environment.yml

update:
    conda env update -f environment.yml --prune

test:
    python -m pytest

coverage:
    python -m pytest --cov=MoSiR --cov-report=term-missing

.PHONY: init update test coverage
