#define NUITKA_COMPANY_NAME "Bureau du Forestier en chef"
#define NUITKA_PRODUCT_NAME "MoSiR"
#define NUITKA_VERSION_COMBINED "1.0.0.0"
#define _NUITKA_ONEFILE_ARCHIVE_BOOL 0
#define _NUITKA_ONEFILE_BUILD_BOOL 1
#define _NUITKA_ONEFILE_CHILD_GRACE_TIME_INT 5000
#define _NUITKA_ONEFILE_COMPRESSION_BOOL 1
#define _NUITKA_ONEFILE_SPLASH_SCREEN 1
#define _NUITKA_ONEFILE_TEMP_BOOL 1
#define _NUITKA_ONEFILE_TEMP_SPEC "%TEMP%\\onefile_%PID%_%TIME%"
